// These are the files to override if we use solidity compiler < v0.8.20
export const filesToOverride = [
    "contracts/test/TestERC721Token.sol",
    "contracts/test/TestToken.sol",
    "@openzeppelin/contracts/token/ERC721/ERC721.sol",
    "@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol",
    "@openzeppelin/contracts/token/ERC721/IERC721.sol",
    "@openzeppelin/contracts/utils/introspection/IERC165.sol",
    "@openzeppelin/contracts/utils/introspection/ERC165.sol",
    "@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol",
    "@openzeppelin/contracts/interfaces/draft-IERC6093.sol",
    "@openzeppelin/contracts/token/ERC20/ERC20.sol",
    "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
    "@openzeppelin/contracts/token/ERC20/extensions/IERC20Permit.sol",
    "@openzeppelin/contracts/utils/cryptography/EIP712.sol",
    "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol",
    "@openzeppelin/contracts/utils/Strings.sol",
    "@openzeppelin/contracts/utils/math/SignedMath.sol",
    "@openzeppelin/contracts/utils/math/Math.sol",
    "@openzeppelin/contracts/utils/ShortStrings.sol",
    "@openzeppelin/contracts/utils/StorageSlot.sol",
    "@openzeppelin/contracts/interfaces/IERC5267.sol",
    "@openzeppelin/contracts/utils/cryptography/ECDSA.sol",
    "@openzeppelin/contracts/utils/Nonces.sol",
    "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol",
    "@openzeppelin/contracts/token/ERC20/IERC20.sol",
    "@openzeppelin/contracts/utils/Context.sol",
]
