name: safe-modules
on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: |
          pnpm install
          pnpm run fmt:global-check
          # -i is to ignore packages that are expected to have multiple versions across the workspace
          npx sherif@0.9.0 -i @openzeppelin/contracts
