name: 4337 End-to-End Tests With Upstream Bundler
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # There's no direct way to schedule the job run every 2 weeks, instead we schedule it on the 1st and 15th of every month. The trick is taken from https://stackoverflow.com/a/46233330/7820085
    - cron: '30 1 1,15 * *'
  push:
    paths:
      - 'modules/4337/**'
      - 'modules/passkey/**'
      - 'packages/4337-local-bundler/**'

jobs:
  e2e-upstream-bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: |
          pnpm install
          pnpm run --filter "{modules/4337}" --filter "{modules/passkey}" test:4337:upstream
