name: safe-modules-4337-local-bundler
on:
  push:
    paths:
      - 'packages/4337-local-bundler/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: |
          pnpm install
          pnpm run --filter "@safe-global/safe-4337-local-bundler" lint
