name: safe-modules-4337-passkey-example
on:
  push:
    paths:
      - 'modules/4337/**'
      - 'modules/passkey/**'
      - 'examples/4337-passkeys/**'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: |
          pnpm install
          pnpm run --filter "@safe-global/safe-modules-example-4337-passkeys" lint
          pnpm run --filter "@safe-global/safe-modules-example-4337-passkeys" build
        env:
          VITE_WC_CLOUD_PROJECT_ID: ${{ secrets.VITE_WC_CLOUD_PROJECT_ID }}
          VITE_WC_4337_BUNDLER_URL: ${{ secrets.VITE_WC_4337_BUNDLER_URL }}
