name: safe-modules-recovery
on:
  push:
    paths:
      - 'modules/recovery/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run coverage -w modules/recovery
      - uses: coverallsapp/github-action@master
        with:
          path-to-lcov: modules/recovery/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint -w modules/recovery
      - run: npm run fmt:check -w modules/recovery
      - run: npm run build -w modules/recovery
