name: safe-modules-recovery
on:
  push:
    paths:
      - 'modules/recovery/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: |
          pnpm install --frozen-lockfile
          pnpm run --filter "@safe-global/safe-recovery" lint
